### ISSUE TITLE
Koding VM instance will not turn on. Have contacted support at Koding.com

### ISSUE THREAD

**Issue by cool2learn** [gdhorne/cloud-computing-development-environment#1]

**Comment by gdhorne** [comment]
After logging into the Koding.com website you should see the virtual machine name (koding-vm-0 is the default name) near the upper left edge of the web browser window. Normally, you will be presented with a pop-up window with a button labelled "TURN IT ON" which you should click. However, if you do not get this widow, then beside the name "koding-vm-0" you will see a circle with three dots just to the right of the virtual machine name. Click on the circle and you can toggle the virtual machine on and off.

I just signed into my account and received the pop-up window. Do you see the default name 'koding-vm-0" in the upper left portion of the web browser wndow? I will check-in on the Cloud Computing Part I forums throughout the day.

**Comment by cool2learn** [comment]
Gregory,

I get the pop-up window asking me to click the button. I came back the next day and discovered the VM was up and running with the 4 panes you presented in your instructions. I'm in the midst of a job transition so I could not use the VM at the time. When I came back it had been turned off due to inactivity. How long does it take to spin up one of these VMs once you click the Turn It On button? 

I'm surprised it's taking multiple hours. 

On Thursday, March 5, 2015 11:50 AM, Gregory D. Horne notifications@github.com wrote:

After logging into the Koding.com website you should see the virtual machine name (koding-vm-0 is the default name) near the upper left edge of the web browser window. Normally, you will be presented with a pop-up window with a button labelled "TURN IT ON" which you should click. However, if you do not get this widow, then beside the name "koding-vm-0" you will see a circle with three dots just to the right of the virtual machine name. Click on the circle and you can toggle the virtual machine on and off.
I just signed into my account and received the pop-up window. Do you see the default name 'koding-vm-0" in the upper left portion of the web browser wndow? I will check-in on the Cloud Computing Part I forums throughout the day.

**Comment by gdhorne** [comment]
The VM has always spun-up within 5 minutes any time I have attempted to start it from stopped state. It is possible your VM is on a heavily-loaded physical server although I doubt a multi-hour spin-up would ever occur in the worst case load.

If you have access to a terminal session I suggest you try rebooting your VM from the command-line.

$ sudo reboot

This should resolve the slow spin-up time. I had a similar issue at one point last month and a reboot resolved the non-responsiveness.

A second option if the VM is spinning up and taking a more than 15 minutes to be in ready state, you can click on the three dots in the circle to the right of the VM name (koding-vm-0 by default) along the left-edge of the webpage and select the shut-down option. Let the VM fully shut-down before trying to manually restart it.

You might have to continue working with the support staff at Koding.com. I have no idea how many of the Coursera students sign-up for accounts and are running their VMs at any given time. I will login to Koding.com this evening but if you do not see another message from me then you can presume there was no delay when spinning up my own virtual machine.

**Comment by gdhorne** [comment]
I was able to spin-up my own VM in under 3 minutes after responding to your message.

**Comment by cool2learn** [comment]
Gregory,

I submitted a ticket and Koding support sent a video of their support staff starting up my VM. In the recording, it took under 3 minutes. Of note, I never get any of the startup messages that you mentioned in your directions or what I observed in their recording of my VM's startup. I've disabled popup blocker on Firefox 36 running on Ubuntu 14.04. 

I wanted to attempt the assignment but that's not going to happen at this point. I'll try it once I can get past these issues but for no credit. I'll be studying for the exam this week. Thanks for your efforts.

On Saturday, March 7, 2015 10:36 PM, Gregory D. Horne notifications@github.com wrote:

I was able to spin-up my own VM in under 3 minutes after responding to your message.

**Comment by gdhorne** [comment]
Maybe switching to Google Chrome would  resolve the issue. I am using Google Chrome every time I login to Koding. On the bright-side you can always complete the optional programming assignment after the course wraps-up for your own benefit and in preparation for Cloud Computing Concepts - Part 2.

Based on you experience I will be updating the instructions explicitly recommending people use Google Chrome if their current web browser causes lengthy virtual machine start-up times when interacting with Koding.com.

**Comment by gdhorne** [comment]
Closing this thread.

**Comment by cool2learn** [comment]
Gregory,

Thanks for the feedback. I'll try Google Chrome and let you know the results. I plan on taking all of the courses in the series and want to resolve this issue for future programming assignments in the other courses. 

Regards,
Carl Ely

On Monday, March 9, 2015 9:31 AM, Gregory D. Horne notifications@github.com wrote:

Maybe switching to Google Chrome would  resolve the issue. I am using Google Chrome every time I login to Koding. On the bright-side you can always complete the optional programming assignment after the course wraps-up for your own benefit and in preparation for Cloud Computing Concepts - Part 2.
Based on you experience I will be updating the instructions explicitly recommending people use Google Chrome if their current web browser causes lengthy virtual machine start-up times when interacting with Koding.com.

**Comment by cool2learn** [comment]
Gregory,

Tech support at Koding was stumped with FF 36 on Ubuntu 14.04 not working. They suggested FF 36 install corruption or Add-ON could be causing an issue if Google Chrome worked on the same machine that was running FF36. 

I can confirm that Google Chrome enabled me to Turn on the VM. I got the VM building message for 3 minutes then was presented with the 4 panes you mentioned in your instructions. I was able to sudo poweroff the VM from within the terminal pane, and restart the VM a 2nd time. 

I'll try and determine why my version of FF is failing because Tech support said that should work because they used FF 36 on Ubuntu 14.04 to launch my VM. Maybe you can add those instructions for FF users.

Regards,
Carl Ely

On Monday, March 9, 2015 9:32 AM, Gregory D. Horne notifications@github.com wrote:

Maybe switching to Google Chrome would  resolve the issue. I am using Google Chrome every time I login to Koding. On the bright-side you can always complete the optional programming assignment after the course wraps-up for your own benefit and in preparation for Cloud Computing Concepts - Part 2.
Based on you experience I will be updating the instructions explicitly recommending people use Google Chrome if their current web browser causes lengthy virtual machine start-up times when interacting with Koding.com.
